### PR TITLE
Added support for WASI and integrated into WAPM

### PR DESCRIPTION
**Pull request by syrusakbary**
This PR adds support for exporting into WebAssembly/WASI, so the package can be distributed as a `.wasm` binary and executed universally (in Mac, Linux and Windows) using [wasmer](https://github.com/wasmerio/wasmer).

I already published the first version of the package on WAPM so people can install and use it.
WAPM package page: https://wapm.io/package/viu

## Instructions

1. Install Wasmer+wapm
```
curl https://get.wasmer.io -sSfL | sh
```

2. Install viu with wapm
```
wapm install -g viu
```

3. Run viu

```
viu --dir=. img/explode.gif
```

> Note: Why the `--dir=.` is needed? Because WASI establish a set of permissions on top of directories, and as we want the wasm file to access the file, we need to explicitly add permissions to it.

## Publish

To publish next versions of the package in wapm, just do:

```
wapm publish
```

### CODE REVIEW

**Comment by atanunq** [comment]
Hi, thank you for contributing!
I have only heard of WebAssembly before and that is why I am taking my time to play around with your changes. If the project is build for a specific target (say Windows) with `cargo build` won't that lead to the same result? Excuse my lack of knowledge, but why is the other [repo](https://github.com/wapm-packages/viu) required as well as the new readme?

That is quite a lot of questions but I will appreciate if you could shed some light and help me understand. Thanks in advance!

**Comment by syrusakbary** [comment]
> If the project is build for a specific target (say Windows) with cargo build won't that lead to the same result?
Kind of. What WebAssembly/WASI is doing is that rather than having to compile the program to multiple different targets (let's say windows, mac and linux), generating three different executables (one for each platform)... will generate only one binary `viu.wasm` that can be executed across any platform (an universal binary).

> but why is the other repo required as well as the new readme?
The other readme is only used for the wapm.io page: https://wapm.io/package/viu

But... why use other readme for wapm?
The execution differs a bit when running it with wapm (because of the `--dir=.` extra argument), and also I wanted to showcase first how easy is for people to use it (and adding build instructions specialized for WASI at the end).

If you want, I can change this PR to have only one README, but I thought having two was more convenient.

Looking forward hearing your thoughts!

**Comment by atanunq** [comment]
Thank you for the clarifications! I would really like to stay as minimalistic as possible so one readme would be great.
It is an interesting concept, what you are trying to achieve with the universal binary. It would be an honour to be one of the early adopters!

**Comment by syrusakbary** [comment]
Awesome, I just removed the WASI readme.

Let me know if you have more suggestions :)

**Comment by syrusakbary** [comment]
@atanunq *ping :)

**Comment by atanunq** [comment]
Sorry, I have been busy. I will merge it this weekend, thanks for the contribution and reminder!

**Pull request merged**
